

race_dict = {
    'dwarf': 1,
    'elf': 2,
    'halfling': 3,
    'human': 4,
    'dragonborn': 5,
    'gnome': 6,
    'half-elf': 7,
    'half-orc': 8,
    'tiefling': 9,
}

ability_score_dict = {"str": 1, "dex": 2, "con": 3, "int": 4, "wis": 5, "cha": 6}

skill_dict = {
        "acrobatics": 1,
        "animal handling": 2,
        "arcana": 3,
        "athletics": 4,
        "deception": 5,
        "history": 6,
        "insight": 7,
        "intimidation": 8,
        "investigation": 9,
        "medicine": 10,
        "nature": 11,
        "perception": 12,
        "performance": 13,
        "persuasion": 14,
        "religion": 15,
        "sleight of hand": 16,
        "stealth": 17,
        "survival": 18,
    }

proficieny_dict = {
        "light armor": 1,
        "medium armor": 2,
        "heavy armor": 3,
        "all armor": 4,
        "padded": 5,
        "leather": 6,
        "studded leather": 7,
        "hide": 8,
        "chain shirt": 9,
        "scale mail": 10,
        "breastplate": 11,
        "half plate": 12,
        "ring mail": 13,
        "chain mail": 14,
        "splint": 15,
        "plate": 16,
        "shield": 17,
        "shields": 18,
        "simple weapons": 19,
        "martial weapons": 20,
        "clubs": 21,
        "daggers": 22,
        "greatclubs": 23,
        "handaxes": 24,
        "javelins": 25,
        "light hammers": 26,
        "maces": 27,
        "quarterstaffs": 28,
        "sickles": 29,
        "spears": 30,
        "crossbows, light": 31,
        "darts": 32,
        "shortbows": 33,
        "slings": 34,
        "battleaxes": 35,
        "flails": 36,
        "glaives": 37,
        "greataxes": 38,
        "greatswords": 39,
        "halberds": 40,
        "lances": 41,
        "longswords": 42,
        "mauls": 43,
        "morningstars": 44,
        "pikes": 45,
        "rapiers": 46,
        "scimitars": 47,
        "shortswords": 48,
        "tridents": 49,
        "war picks": 50,
        "warhammers": 51,
        "whips": 52,
        "blowguns": 53,
        "crossbows, hand": 54,
        "crossbows, heavy": 55,
        "longbows": 56,
        "nets": 57,
        "alchemist's supplies": 58,
        "brewer's supplies": 59,
        "calligrapher's supplies": 60,
        "carpenter's tools": 61,
        "cartographer's tools": 62,
        "cobbler's tools": 63,
        "cook's utensils": 64,
        "glassblower's tools": 65,
        "jeweler's tools": 66,
        "leatherworker's tools": 67,
        "mason's tools": 68,
        "painter's supplies": 69,
        "potter's tools": 70,
        "smith's tools": 71,
        "tinker's tools": 72,
        "weaver's tools": 73,
        "woodcarver's tools": 74,
        "disguise kit": 75,
        "forgery kit": 76,
        "dice set": 77,
        "dragonchess set": 78,
        "playing card set": 79,
        "three-dragon ante set": 80,
        "bagpipes": 81,
        "drum": 82,
        "dulcimer": 83,
        "flute": 84,
        "lute": 85,
        "lyre": 86,
        "horn": 87,
        "pan flute": 88,
        "shawm": 89,
        "viol": 90,
        "disguise kit": 91,
        "forgery kit": 92,
        "herbalism kit": 93,
        "navigator's tools": 94,
        "poisoner's kit": 95,
        "thieves' tools": 96,
        "land vehicles": 97,
        "water vehicles": 98,
        "saving throw: str": 99,
        "saving throw: dex": 100,
        "saving throw: con": 101,
        "saving throw: int": 102,
        "saving throw: wis": 103,
        "saving throw: cha": 104,
        "skill: acrobatics": 105,
        "skill: animal handling": 106,
        "skill: arcana": 107,
        "skill: athletics": 108,
        "skill: deception": 109,
        "skill: history": 110,
        "skill: insight": 111,
        "skill: intimidation": 112,
        "skill: investigation": 113,
        "skill: medicine": 114,
        "skill: nature": 115,
        "skill: perception": 116,
        "skill: performance": 117,
        "skill: persuasion": 118,
        "skill: religion": 119,
        "skill: sleight of hand": 120,
        "skill: stealth": 121,
        "skill: survival": 122,
    }

language_dict = {
        "common": 1,
        "dwarvish": 2,
        "elvish": 3,
        "giant": 4,
        "gnomish": 5,
        "goblin": 6,
        "halfling": 7,
        "orc": 8,
        "abyssal": 9,
        "celestial": 10,
        "draconic": 11,
        "deep speech": 12,
        "infernal": 13,
        "primordial": 14,
        "sylvan": 15,
        "undercommon": 16,
    }